// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmfXe-JhD0Ix76kzxyIouTw8yGmKf9JeE',
    appId: '1:142339791250:web:58eef51ed3f14d4414894b',
    messagingSenderId: '142339791250',
    projectId: 'dslab-f23b7',
    authDomain: 'dslab-f23b7.firebaseapp.com',
    storageBucket: 'dslab-f23b7.appspot.com',
    measurementId: 'G-CPL8VVXCVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSfnrddl5TVyFA7lfgyQ0rZ0nNRkO6Frc',
    appId: '1:142339791250:android:5fd611aace7c5d1c14894b',
    messagingSenderId: '142339791250',
    projectId: 'dslab-f23b7',
    storageBucket: 'dslab-f23b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy-hE4o_vqTA5xyhkGRWKEWYcXACwpGns',
    appId: '1:142339791250:ios:d24f2b6c05711d3b14894b',
    messagingSenderId: '142339791250',
    projectId: 'dslab-f23b7',
    storageBucket: 'dslab-f23b7.appspot.com',
    androidClientId: '142339791250-6k4gkod2a85psa5d781l0pt2pdm6fm8e.apps.googleusercontent.com',
    iosClientId: '142339791250-5g38qld048jlcvarvgftscn3d5bgr8va.apps.googleusercontent.com',
    iosBundleId: 'com.example.dslab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy-hE4o_vqTA5xyhkGRWKEWYcXACwpGns',
    appId: '1:142339791250:ios:2b7eb513a6567e8414894b',
    messagingSenderId: '142339791250',
    projectId: 'dslab-f23b7',
    storageBucket: 'dslab-f23b7.appspot.com',
    androidClientId: '142339791250-6k4gkod2a85psa5d781l0pt2pdm6fm8e.apps.googleusercontent.com',
    iosClientId: '142339791250-s4v8q7i6qppcpv4v2a17u1qc97sdkpmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dslab.RunnerTests',
  );
}
